### ISSUE TITLE
Circular Import Issue (chemprop.featurizers)

### ISSUE THREAD

**Issue by Taohid-bhuiya** [chemprop/chemprop#1174]
Hi,

I was running Chemprop without any issues then suddenly I started to encounter an ImportError when running Chemprop. The error suggests a circular import issue in chemprop.featurizers whereas I haven't made any changes regarding that or in Chemprop directory.  Below is the exact error message:

<img width="700" alt="Image" src="https://github.com/user-attachments/assets/3567bf8a-e8f4-4117-b573-e62b1ecdd08a" />

**Steps to Reproduce:**
Run python -c "from chemprop.featurizers import Featurizer; print('Success!')"
Observe the ImportError

**System Information**
OS: Windows
Python Version: Python 3.11.5
Chemprop Version: 2.1.1

**Comment by JacksonBurns** [comment]
I'm not able to reproduce this locally with the version of chemprop 2.1.1 on PyPI:
```bash
(chemprop_v2_live) jackson@jackson-Precision-7540:~$ python  # try and import it after importing chemprop
Python 3.11.11 | packaged by conda-forge | (main, Dec  5 2024, 14:17:24) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chemprop
>>> chemprop.__version__
'2.1.1'
>>> from chemprop.featurizers import Featurizer
>>> exit()
(chemprop_v2_live) jackson@jackson-Precision-7540:~$ python  # try and import it directly
Python 3.11.11 | packaged by conda-forge | (main, Dec  5 2024, 14:17:24) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from chemprop.featurizers import Featurizer
>>> exit()
(chemprop_v2_live) jackson@jackson-Precision-7540:~$ pip list | grep chemprop  # confirm chemprop version
chemprop                 2.1.1
(chemprop_v2_live) jackson@jackson-Precision-7540:~$ python -c "from chemprop.featurizers import Featurizer"  # yours
(chemprop_v2_live) jackson@jackson-Precision-7540:~$
```

Do you have any changes locally - is this installed from PyPI or source?

**Comment by Taohid-bhuiya** [comment]
I had it installed from source, I didn't make any changes locally. I also forced reinstall chemprop to make sure no change was there. But as I mentioned, it was working in my local also, and suddenly it's not working.

However, I installed from PyPI now and it seems PyPI version is working.

**Comment by JacksonBurns** [comment]
May need to double check `git status` to see if you have any local changes.

Could you also show the current commit you are on? It's possible that chemprop v2.1.1+(whatever we have committed since then) has this issue but not 2.1.1 exactly.

**Comment by Taohid-bhuiya** [comment]
Actually when I had the issue I was on chemprop version 2.1.0. Then I installed the latest version to check if that solve the issue.
You can check the version I currently have below-

<img width="340" alt="Image" src="https://github.com/user-attachments/assets/a72ed4f1-98aa-44c6-9f14-08f191d6905c" />

**Comment by JacksonBurns** [comment]
So you're on main - I installed in a fresh python environment with `pip install "git+https://github.com/chemprop/chemprop.git@main"` and the import worked for me.

We have seen this exact error before (https://github.com/chemprop/chemprop/pull/887) and it should be resolved in the latest version (and is for me).

It's still possible that your local repo doesn't reflect all the remote changes. You might need to do a hard reset, or just delete and re-clone.

**Comment by Taohid-bhuiya** [comment]
Once I had the issue I did delete and re-clone several times but that didn't fix the issue for me. But the same clone also was working until I had the error so I am unsure what caused it. As the PyPI installation working, I will work on that for now.
